In [1]:
import numpy as np

In [2]:
import os

In [3]:
import pandas as pd

In [4]:
from sklearn.cluster import bicluster

---

In [5]:
dfFile = os.path.join('..', 'data', 'user_gen', 'siRNA_binary_dataframe.txt')

In [6]:
RNAiDf = pd.read_table(dfFile, index_col=0)

In [7]:
RNAiMatrix = RNAiDf.values  # binarized so no NaN

In [9]:
RNAiMatrix.shape

(24866, 13)

In [9]:
np.unique(RNAiMatrix)

array([0, 1])

In [8]:
np.sum(RNAiMatrix, axis=0)

array([ 756, 1450, 1141, 1219, 3619, 1060, 2095, 3092, 1795, 2844, 2830,
       1673, 2525])

In [8]:
RNAiDf.isnull().sum().sum()

0

This confirms that there are not NaN values.

# Spectral Co-Clustering

In [9]:
numBiclust = 10

In [9]:
model = bicluster.SpectralCoclustering()

In [10]:
model.fit(RNAiMatrix)

ValueError: array must not contain infs or NaNs

# Spectral Biclustering

In [9]:
RNAiMatrix = RNAiMatrix.astype(float)

In [10]:
np.unique(RNAiMatrix)

array([ 0.,  1.])

In [11]:
model = bicluster.SpectralBiclustering()

In [12]:
model.fit(RNAiMatrix)

ValueError: array must not contain infs or NaNs